### ISSUE TITLE
plugin architecture

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/generic-extractor#21]
pokud chce generickej extraktor podporovat pluginy, bylo by dobrý aby
### bylo jasně v konfiguraci vidět, že se používá nějakej plugin a kde

tj. místo 

```
parameters:
    config:
        jobs:
        - 
            endpoint: "insights"
            scroller: none
            # tohle je plugin
            parser:
                method: "facebook.insights"
            dataType: "insights"
            dataField: "data"
```

```
parameters:
    config:
        jobs:
        - 
            endpoint: "insights"
            scroller: none
            plugins:
            - 
                name: "facebook.insights"
                parameter1: value1
            dataType: "insights"
            dataField: "data"
```
### bylo jasně zadefinovaný, kde pluginy můžou bejt

a to jak na straně dokumentace konfigurace, tak na straně dokumentace vývoje pluginu
### byl vývoj pluginu snadnej

abych nemusel mít repozitář s generickým extraktorem, z něho referencovanej repozitář s pluginem a nějak to commitoval, pushoval a composer updatoval dokolečka. 

vyvíjet by se mělo z repozitáře pluginu, odtud bys měl mít možnost spustit generickej extraktor s aktuální verzí pluginu (docker-compose s namountováním současnýho folderu)
