### ISSUE TITLE
ex-salesforce

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/generic-extractor#22]
1) oauth data (z oauth api) a nebo refresh token request vrací 

```
{
  "access_token": "***",
  "signature": "***",
  "scope": "refresh_token web api",
  "instance_url": "https://na12.salesforce.com",
  "id": "https://login.salesforce.com/id/00DU0000000XwVIMA0/005U0000000aHQnIAM",
  "token_type": "Bearer",
  "issued_at": "1464069257502"
}
```

z jednoho z nich potřebuju dostat nejen `access_token`, ale i `instance_url`, která vytváří `baseUrl`

2) login type `oauth20.login` nastavuje hlavičku `Authorization` a do ní potřebuju concatnout `"Bearer " access_token`, teď je možné tam dát pouze access token

```
        authentication: 
            type: "oauth20.login"
            loginRequest:
                endpoint: https://login.salesforce.com/services/oauth2/token
                params: 
                    grant_type: refresh_token
                    client_id: "******"
                    client_secret: "******"
                    refresh_token: "*****"
                method: FORM
            apiRequest:
                headers:
                    Authorization:
                        function: concat
                        args: 
                            - 'Bearer '
                            - !!! ACCESS_TOKEN !!!
```

3) primární klíč

```
 jobs: 
        - 
            endpoint: "query"
            dataType: "User"
            dataField: "records"
            params:
                q: "SELECT Id, Name, UserRoleId FROM User"
```

bylo by fajn, kdybych mohl říct, že `Id` je primární klíč a neřešit mapping pro zbývající sloupce, nicméně bylo by možné v UI doplnit mapping
