### ISSUE TITLE
ex-facebook

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/generic-extractor#23]
1) primární klíče

```
        jobs: 
        - 
            endpoint: "."
            dataType: "page"
            dataField: "."
            params:
                fields: "id,name,about,affiliation,artists_we_like,attire,band_interests,band_members,best_page,bio,birthday,booking_agent,built,business,can_checkin,can_post,category,category_list,checkins,company_overview,contact_address,country_page_likes,culinary_team,description,directed_by,display_subtext,engagement,fan_count,featured_video,features,food_styles,founded,general_info,general_manager,genre,global_brand_page_name,global_brand_root_id,has_added_app,hometown,hours,impressum,influences,is_always_open,is_community_page,is_permanently_closed,is_published,is_unclaimed,is_verified,last_used_time,link,location,members,mission,mpg,name_with_location_descriptor,network,new_like_count,offer_eligible,owner_business,parent_page,parking,payment_options,personal_info,personal_interests,pharma_safety_info,phone,place_type,plot_outline,press_contact,price_range,produced_by,products,promotion_eligible,promotion_ineligible_reason,public_transit,record_label,release_date,restaurant_services,restaurant_specialties,schedule,screenplay_by,season,single_line_address,starring,start_info,store_location_descriptor,store_number,studio,access_token,talking_about_count,unread_message_count,unread_notif_count,unseen_message_count,username,verification_status,voip_info,website,written_by,were_here_count"  
```

vím, že `id` je primární klíč, ale zbylé fields jsou mi neznáme a nemůžu na ně napsat kilometrový mapping

1b) primární klíče pro děcka

už to prostě vím

```
        - 
            # PK = id
            endpoint: "insights"
            scroller: none
            parser:
                method: "facebook.insights"
            dataType: "insights"
            dataField: "data"
            children:
            -   
                # PK = id + end_date
                endpoint: "/v2.6/{1\:id}"
                scroller: none
                placeholders:
                    "1\:id": "id"
                params:
                        since: previousStart
                parser:
                    method: "facebook.insights"
                dataType: "insights"
                dataField: "data"
```

2) inkrementy + backfill

```
        - 
            # PK = id + end_date, end date nutno doplnit v pluginu
            endpoint: "insights"
            scroller: none
            parser:
                method: "facebook.insights"
            dataType: "insights"
            dataField: "data"
            # zkusit cyklovat po jednotlivejch metrikách
            children:
            -   
                endpoint: "/v2.6/{1\:id}"
                scroller: none
                placeholders:
                    "1\:id": "id"
                params:
                    since: "2015-01-01"
                parser:
                    method: "facebook.insights"
                dataType: "insights"
                dataField: "data"
```

můžu říct, že se první stažení má udělat od 2015-01-01, ale další už by měly být od `previousStart`

```
            -   
                endpoint: "/v2.6/{1\:id}"
                scroller: none
                placeholders:
                    "1\:id": "id"
                params:
                    since: 
                        value: previousStart
                        default: 2015-01-01
```

3) stránkování a jeho stopnutí (není nutné)

mám request, kde je ?since=2016-01-01&until=2016-02-01 a další stránky ukazují na měsíce dopředu, ale nezastaví se to na aktuálním datu a když to překročí 93 dní od současného, tak to zahučí s errorem. potřeboval bych teda zkontorlovat, ať since nepřekročí dnešní datum.
